### ISSUE TITLE
Cannot save after adding/deleting symbols

### ISSUE THREAD

**Issue by robot-from-outer-space** [jefdongus/insert-symbols-anki-addon#3] opened 2020-01-15 19:18 UTC
Hi jefdongus,
first of all, I love your addon! It's great : ) Such a time saver. I use it constantly.

However, I have two issues:

1. The greek letter ɛ is incorrectly spelled "Episilon" instead of "Epsilon" (with an additional i) in the predefined list, which makes using it difficult

2. Changing the list of symbols leads to the error message shown below. For e.g. I add a new symbol or remove an old one. As soon as I click on "Ok" to exit the settings dialogue, I get the error.

**Debug info:**
Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\2040501954\symbol_window.py", line 285, in accept
    self._save()
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\2040501954\symbol_window.py", line 259, in _save
    self._working_list)
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\2040501954\symbol_manager.py", line 128, in update_and_save_symbol_list
    self._save_to_db()
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\2040501954\symbol_manager.py", line 238, in _save_to_db
    self._db.execute("delete from %s" % self.TBL_NAME)
  File "anki\db.py", line 32, in execute
<class 'sqlite3.ProgrammingError'>: Cannot operate on a closed database.

**Comment by jefdongus** [comment] 2020-01-18 00:46
Nice catch on the spelling error! Will fix.

As for the issue regarding saving, has this occurred every time or only in some cases? If you have made changes to the symbol list previously, I would make a backup by exporting them, then uninstall and reinstall the plugin. If that still doesn't work, could you provide a list of the plugins that you are using?

**Comment by AnKingMed** [comment] 2020-01-27 20:52
I get the same error when clicking Ok

**Comment by jefdongus** [comment] 2020-01-29 04:15
Thanks for letting me know. Could you provide some more info, including:
1. Your Anki verson and operating system
2. Other plugins that you are using
3. Whether this occurs all the time or only sometimes? If it's the latter, could you let me know which steps recreate this problem?

**Comment by AnKingMed** [comment] 2020-01-29 04:21
1. I'm on 2.1.20beta6
2. I have a ton.. but it does it even when other add-ons are turned off
3. It occurs all the time. Ever time I try to add or delete a symbol and click "ok" it gives the error message

**Comment by jefdongus** [comment] 2020-01-29 05:50
Ok, after some digging around Anki's source code, I was able to reproduce the bug. Turns out this occurs when you try to modify the symbol list after a sync operation, since that closes and re-opens the database. 

I don't have time to work on a fix now, but I've added an error message to alert users to the problem (to avoid this, make modifications to the symbol list _before_ hitting the Sync button).

**Comment by AnKingMed** [comment] 2020-01-29 13:06
Thanks for looking into it! This is an easy enough fix for the time being

**Comment by jefdongus** [comment] 2020-03-02 18:03
This should be fixed in the latest update. Please let me know if any issues arise!

**Comment by AnKingMed** [comment] 2020-03-02 19:27
Awesome thanks!

**Closed** 2020-03-06 15:27 UTC
Labels: bug
