### ISSUE TITLE
won't let me type in the browser without an error

### ISSUE THREAD

**Issue by silentcicada1** [jefdongus/insert-symbols-anki-addon#8] opened 2020-03-14 00:26 UTC
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.21 (8960d12a) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-13 15:49:13
Add-ons possibly involved: ⁨Symbols As You Type⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/silentcicada/Library/Application Support/Anki2/addons21/2040501954/browser_replacer.py", line 32, in on_text_edited
    self._check_for_replacement(current_text, False)
  File "/Users/silentcicada/Library/Application Support/Anki2/addons21/2040501954/browser_replacer.py", line 52, in _check_for_replacement
    cursor_pos = self._search_box.cursorPosition()
RuntimeError: wrapped C/C++ object of type QLineEdit has been deleted

**Comment by jefdongus** [comment] 2020-03-18 03:41
Duplicate of #4 

Just released an update that *hopefully* fixes the issue. But if not, if you wouldn't mind posting what actions you took just prior to the error, that would be great!

**Comment by silentcicada1** [comment] 2020-03-21 15:45
I haven't had the error since the update. Thank you! I will keep better track of the actions that lead to the error if it happens in the future

**Comment by jefdongus** [comment] 2020-03-22 15:09
Glad to hear that! Please feel free to let me know if anything else comes up!

**Closed by jefdongus** 2020-03-22 15:09 UTC
Labels: duplicate
